### ISSUE TITLE
增加离线读hfile的模式

### ISSUE THREAD

**Issue by casperit** [analysys/presto-hbase-connector#1]
1. 目前的hbase connector是基于regionserver rpc handler,presto查询会影响已有在线业务
2. 希望能够增加离线读hfile的方式,避免对在线handler的消耗

**Comment by Crossoverrr** [comment]
正在从商业版中抽离代码，还请耐心等待 :)
目前以商业版的测试结果来说，使用ClientSideScanner确实能极大的减少网络资源的消耗，而且对性能也有一定的提升，尤其是需要扫描大量字段的场景。

**Comment by 0xcafedaddy** [comment]
请问现在抽离代码的进度如何？大概什么时候可用啊？

**Comment by Crossoverrr** [comment]
首先感谢您的关注！
很抱歉的是，前段时间确实有些事情耽误了，我会尽快完成抽离，争取在下周将这个版本开放出来。

**Comment by 0xcafedaddy** [comment]
> 首先感谢您的关注！
> 很抱歉的是，前段时间确实有些事情耽误了，我会尽快完成抽离，争取在下周将这个版本开放出来。

很棒！期待这个功能的开放！

**Comment by Crossoverrr** [comment]
各位，ClientSideRegionScanner查询已经实现了，具体步骤可以在README文档中查看。
