### ISSUE TITLE
Table has no columns:

### ISSUE THREAD

**Issue by Mvink123** [analysys/presto-hbase-connector#2]
***Query 20190318_114214_00006_ij286 failed: Table has no columns: hbase:HBaseTableHandle{schemaTableName=default.test4}***
您好，我在hbase的default的namespace里建了一个test4表，按照文档配置好test4.json后，查询出现这样的错误提示，请问是错在哪儿呢？
- test4.json配置
```json
{
  "tableName": "test4",
  "schemaName": "default",
  "rowKeyFormat": "name,age",
  "rowKeySaltUpperAndLower": "0,29",
  "describe": "Table for test!",
  "columns": [{
    "family": "cf",
    "columnName": "rowkey",
    "comment": "Column for test4!",
    "type": "varchar",
    "isRowKey": true
  }, {
    "family": "cf",
    "columnName": "name",
    "comment": "Column for test4!",
    "type": "varchar",
    "isRowKey": false
  }, {
    "family": "cf",
    "columnName": "age",
    "comment": "Column for test4!",
    "type": "int",
    "isRowKey": false
  }],
  "rowKeySeparator": "_"
}
```
- hbase.properties配置
```
connector.name=hbase
zookeeper-quorum=172.16.1.243:2181,172.16.1.244:2181,172.16.1.245:2181
zookeeper-client-port=2181
hbase-cluster-distributed=true
presto-server-port=8090
random-schedule-redundant-split=false
meta-dir=/usr/local/meta/chbase
```
- hbase表里是这样的
```
hbase(main):018:0> scan 'test4'
ROW                                              COLUMN+CELL                                                                                                                                 
 miao_30                                         column=cf:age, timestamp=1552471555481, value=30                                                                                            
 miao_30                                         column=cf:name, timestamp=1552471544975, value=miao                                                                                         
1 row(s) in 0.0360 seconds
```

**Comment by Crossoverrr** [comment]
能发一下server.log里的详细报错日志吗？ :)

**Comment by Crossoverrr** [comment]
另外你的rowkey里没有盐值，所以rowKeySaltUpperAndLower这个属性不用配置。
如果配置了rowKeySaltUpperAndLower为"0,29"，rowKey最开始就要加上盐值，变成如下：
00_miao_30
01_xxxx_xx
02_xxxx_xx
...
29_xxxx_xx

**Comment by Crossoverrr** [comment]
问下你的test4.json是放在${meta-dir}目录下吗？

**Comment by kingkongpoon** [comment]
你好，我也遇到了同样的问题。

### 第一presto-cli查询报错
Query 20190719_083152_00004_a28yj failed: Table has no columns: TableHandle {connectorId='hbase', connectorHandle='HBaseTableHandle{schemaTableName=default.test}', layout='Optional.empty'}
desc表的时候，并没有表结构。
presto-cli-0.221-executable.jar --server namenode1:9999 --catalog hbase --schema default

### 第二在mvn编译时test报错
我用的是mvn clean package -Dmaven.test.skip=true生成了
original-presto-hbase-meta-0.1.1.jar
presto-hbase-meta-0.1.1.jar
然后把2个文件放在了presto/plugin/hbase里面

------------------
### 路径配置

#### catalog
>[root@namenode1 catalog]# pwd
/root/tool/opt/presto/etc/catalog

>[root@namenode1 catalog]# ls
hbase.properties  hive.properties  jmx.properties  kafka.properties  mysql.properties

>[root@namenode1 catalog]# cat hbase.properties 
connector.name=hbase
zookeeper-quorum=namenode1:2181,datanode1:2181,datanode2:2181
zookeeper-client-port=2181
zookeeper-znode-parent=/hbase
hbase-cluster-distributed=true
presto-server-port=9999
random-schedule-redundant-split=false
meta-dir=/root/tool/opt/presto/etc/hbase


#### meta
>[root@namenode1 hbase]# pwd
/root/tool/opt/presto/etc/hbase
>[root@namenode1 hbase]# ls
test.json
>[root@namenode1 hbase]# cat test.json 
{
  "tableName": "test",
  "schemaName": "default",
  "rowKeyFormat": "age",
  "describe": "Table for test!",
  "columns": [{
    "family": "cf",
    "columnName": "age",
    "comment": "Column for test!",
    "type": "varchar",
    "isRowKey": true
  }, {
    "family": "cf",
    "columnName": "user",
    "comment": "Column for test!",
    "type": "varchar",
    "isRowKey": false
  }]
}


#### presto-cli查询

>presto:default> show schemas;
       Schema
·--------------------
 default            
 hbase              
 information_schema 
(3 rows)

Query 20190719_084336_00004_b7epf, FINISHED, 3 nodes
Splits: 36 total, 36 done (100.00%)
0:01 [3 rows, 45B] [4 rows/s, 74B/s]

>presto:default> show tables;
      Table
·------------------
 hiveonhbase321   
 kylin_3thvigkwim 
 kylin_6sjc3z1ia3 
 kylin_metadata   
 kylin_uit2rd3ckp 
 test             
(6 rows)

Query 20190719_084347_00005_b7epf, FINISHED, 3 nodes
Splits: 36 total, 36 done (100.00%)
0:00 [6 rows, 182B] [12 rows/s, 382B/s]

>presto:default> desc test;
 Column | Type | Extra | Comment 
·--------+------+-------+---------
(0 rows)

Query 20190719_085410_00015_b7epf, FINISHED, 3 nodes
Splits: 36 total, 36 done (100.00%)
0:01 [0 rows, 0B] [0 rows/s, 0B/s]


>presto:default> select * from test;
Query 20190719_084357_00006_b7epf failed: Table has no columns: TableHandle {connectorId='hbase', connectorHandle='HBaseTableHandle{schemaTableName=default.test}', layout='Optional.empty'}

>presto:default> use hbase;
USE
>presto:hbase> show tables;
   Table   
·-----------
 meta      
 namespace 
(2 rows)

Query 20190719_085248_00011_b7epf, FINISHED, 3 nodes
Splits: 36 total, 36 done (100.00%)
0:00 [2 rows, 43B] [4 rows/s, 105B/s]


------------------
## Hbase

>hbase(main):025:0> list
TABLE                                                                                                                                                                
KYLIN_3THVIGKWIM                                                                                                                                                     
KYLIN_6SJC3Z1IA3                                                                                                                                                     
KYLIN_UIT2RD3CKP                                                                                                                                                     
hiveonhbase321                                                                                                                                                       
kylin_metadata                                                                                                                                                       
test                                                                                                                                                                 
6 row(s) in 0.0260 seconds

=> ["KYLIN_3THVIGKWIM", "KYLIN_6SJC3Z1IA3", "KYLIN_UIT2RD3CKP", "hiveonhbase321", "kylin_metadata", "test"]
>hbase(main):026:0> scan 'test'
ROW                                        COLUMN+CELL                                                                                                               
 abc                                       column=cf:age, timestamp=1559115901716, value=200                                                                         
 abc                                       column=cf:user, timestamp=1559115901716, value=abc                                                                        
 abcdef                                    column=cf:age, timestamp=1560217592342, value=200                                                                         
 abcdef                                    column=cf:sex, timestamp=1560217592342, value=man                                                                         
 abcdef                                    column=cf:user, timestamp=1560217592342, value=abcdef                                                                     
 kktest                                    column=cf:age, timestamp=1559183382346, value=21                                                                          
 kktest                                    column=cf:user, timestamp=1559183382346, value=kktest                                                                     
 kktest1                                   column=cf:age, timestamp=1559183424968, value=21                                                                          
 kktest1                                   column=cf:user, timestamp=1559183424968, value=kktest1                                                                    
 kktest2                                   column=cf:age, timestamp=1559196173354, value=21                                                                          
 kktest2                                   column=cf:sex, timestamp=1559196173354, value=man                                                                         
 kktest2                                   column=cf:user, timestamp=1559196173354, value=kktest2          

------------------

## server.log

>java.lang.Exception: Cannot find meta info of table test.
	at com.analysys.presto.connector.hbase.meta.HBaseTable.<init>(HBaseTable.java:48)
	at com.analysys.presto.connector.hbase.connection.HBaseClientManager.getTable(HBaseClientManager.java:120)
	at com.analysys.presto.connector.hbase.meta.HBaseMetadata.getTableMetadata(HBaseMetadata.java:114)
	at com.analysys.presto.connector.hbase.meta.HBaseMetadata.getTableMetadata(HBaseMetadata.java:107)
	at com.facebook.presto.metadata.MetadataManager.getTableMetadata(MetadataManager.java:478)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:926)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:257)
	at com.facebook.presto.sql.tree.Table.accept(Table.java:53)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:271)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:1852)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1031)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:257)
	at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:127)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:271)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:281)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:746)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:257)
	at com.facebook.presto.sql.tree.Query.accept(Query.java:94)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:271)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:249)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:79)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:71)
	at com.facebook.presto.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:209)
	at com.facebook.presto.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:97)
	at com.facebook.presto.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:744)
	at com.facebook.presto.execution.SqlQueryManager.createQueryInternal(SqlQueryManager.java:366)
	at com.facebook.presto.execution.SqlQueryManager.lambda$createQuery$4(SqlQueryManager.java:305)
	at com.facebook.presto.$gen.Presto_0_221____20190719_084125_1.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Crossoverrr** [comment]
你好，0.1.1版本里位于default库下的表查询会有找不到元数据的问题，这个问题在0.1.2版本已经修复了。

**Comment by Crossoverrr** [comment]
编译完成之后只需要把presto-hbase-meta-0.1.1.jar这个放到相应的插件目录下就好了。

**Comment by kingkongpoon** [comment]
弄了很久都是报那个错，我直接在master编译，还是要在dev_0.1.2编译啊

**Comment by Crossoverrr** [comment]
这两个都是一样的

**Comment by kingkongpoon** [comment]
default的表是能见到，但是就是报Table has no columns，而且namespace我建了多少文件，presto里面除了default的表，就只有schema为hbase的meta和namespace，我怎么建文件夹都不会增加。我上面的信息很全了，研究了2天，还是这样，有空帮忙看看。

**Comment by Crossoverrr** [comment]
切换到0.1.2也是这样吗？

**Comment by Crossoverrr** [comment]
你微信多少方便说一下吗？

**Comment by kingkongpoon** [comment]
QQ3449776645

**Comment by Crossoverrr** [comment]
我加你QQ了，通过一下

**Comment by Crossoverrr** [comment]
@kingkongpoon 组件已经跑通了，那这个issue我就先关闭了，如果再发现新的问题可以再提一个新的issue。
