### ISSUE TITLE
配置无法成功，有版本的关系么

### ISSUE THREAD

**Issue by cmgdmxw** [analysys/presto-hbase-connector#21]
presto> select xwhat, xwho from default.employ;
Query 20191122_055951_00000_nyi4c failed: com.analysys.presto.connector.hbase.schedule.HBaseSplitManager.getSplits(Lcom/facebook/presto/spi/connector/ConnectorTransactionHandle;Lcom/facebook/presto/spi/ConnectorSession;Lcom/facebook/presto/spi/ConnectorTableLayoutHandle;Lcom/facebook/presto/spi/connector/ConnectorSplitManager$SplitSchedulingContext;)Lcom/facebook/presto/spi/ConnectorSplitSource;

表结构目录
default
    employ.json
{
  "tableName": "employ",
  "schemaName": "default",
  "rowKeyFormat": "xwhat,xwho",
  "rowKeySaltUpperAndLower": "0,2",
  "describe": "Table for test!",
  "columns": [{
    "family": "",
    "columnName": "rowkey",
    "comment": "Column for test!",
    "type": "varchar",
    "isRowKey": true
  }, {
    "family": "base",
    "columnName": "xwhat",
    "comment": "Column for test!",
    "type": "varchar",
    "isRowKey": false
  }, {
    "family": "base",
    "columnName": "xwho",
    "comment": "Column for test!",
    "type": "varchar",
    "isRowKey": false
  }],
  "rowKeySeparator": "-"
}

**Comment by Crossoverrr** [comment]
能提供一下你用的presto版本和presto-hbase组件的tag吗？

**Comment by Crossoverrr** [comment]
看报错日志应该是presto版本不兼容的问题，现在最新的版本已经迁移到prestosql的版本了，如果仍然需要使用prestodb的版本，可以使用dev_prestodb-0.220_0.1.2分支的代码构建。
这个问题我先关闭，如果切换版本后还有问题，再打开这个issue吧。
