### ISSUE TITLE
presto-hbase-connector不支持hbase表columName是大小写混合的情况

### ISSUE THREAD

**Issue by GoodJeek** [analysys/presto-hbase-connector#23]
当hbase的表，列名是驼峰形式或者全部是大写的时候，不能查询出结果，这个要怎么处理?

**Comment by Crossoverrr** [comment]
你好，这个是因为presto本身不支持大小写敏感的查询导致的，这个可以修改字段名。也可以修改presto的源代码实现。

**Comment by Crossoverrr** [comment]
暂时关闭这个issue，如果还有问题请再次打开  :)
