### ISSUE TITLE
【帖子】基于0.1.5，支持presto 0.219和hbase 2.0.5的新分支

### ISSUE THREAD

**Issue by wsjz** [analysys/presto-hbase-connector#26]
最近需要用到hbase数据源，发现了易观的hbase connector，但是其中还存在着一些问题，我就直接fork了，目前已修复了一部分问题，以及更新了下文档，之后会持续开发，欢迎交流
地址：https://github.com/wsjz/presto-hbase-connector

**Comment by Crossoverrr** [comment]
[握手][握手][握手]
看到这个issue我非常高兴！欢迎随时把发现的问题，以及优化的思路或者代码等等贡献到这个组件中，让他更加强大！

**Comment by Crossoverrr** [comment]
暂时关闭这个issue，如果还有问题请再次打开  :)
