### ISSUE TITLE
presto表默认未记录hbase的时间戳信息

### ISSUE THREAD

**Issue by wsjz** [analysys/presto-hbase-connector#27]
我看文档里有这样的例子：
delete from hbase.db_test.test_event where xwhen >= 1562139516028;
请问，xwhen是hbase里头timestamp的映射吗？代码里似乎没有相关信息啊
![image](https://user-images.githubusercontent.com/18522955/72504890-b5c4e700-3879-11ea-84c2-fce29d0b39c8.png)
文档里的这个例子，是手动在hbase里创建了xwhen列吗？

**Comment by Crossoverrr** [comment]
是的，这个组件目前还不支持按照时间戳删除数据，xwhen是表中自带的字段。我的想法是，如果要支持按照时间戳获取和删除数据，需要给表指定一个固定名称的字段，就像行键字段一样。

**Comment by Crossoverrr** [comment]
暂时关闭这个issue，如果还有问题可以再次打开  :)
