### ISSUE TITLE
presto表只能显示列名，不会显示列蔟名

### ISSUE THREAD

**Issue by wsjz** [analysys/presto-hbase-connector#28]
![image](https://user-images.githubusercontent.com/18522955/72505341-b5791b80-387a-11ea-9f22-bc608a65512a.png)

presto列名应该带上列蔟名才合理

**Comment by Crossoverrr** [comment]
我明白你的意思，因为组件查询的是hbase的表，所以确实有这个需求。
我了解到的使用组件的人往往是业务人员，他们对字段属于哪个列族往往并不关心，如果要求他们在使用字段时带上列族名，会比较麻烦。我目前考虑可以在备注中注明字段隶属于哪个列族。这个我会持续跟进的。

**Comment by Crossoverrr** [comment]
暂时关闭这个issue，如果还有问题可以再次打开  :)
