### ISSUE TITLE
版本适配的问题

### ISSUE THREAD

**Issue by 0ZhangJc0** [analysys/presto-hbase-connector#41]
您好，我配置好像不成功，运行bin/launcher run命令后问题如下：
**java.util.ServiceConfigurationError: com.facebook.presto.spi.Plugin: Provider com.analysys.presto.connector.hbase.frame.HBasePlugin not a subtype**
prestodb版本：0.228
presto-hbase-connector版本：meta-0.1.3

**Comment by Crossoverrr** [comment]
你好，0.1.3版本是基于prestosql-315版本进行开发的，如果要用prestodb的话可以考虑使用分支dev_prestodb-0.221_0.1.2的代码

**Comment by 0ZhangJc0** [comment]
好的，谢谢您的回复，我已经切换分支了，但是由于prestodb-0.221和_prestodb-0.228的ConnectorPageSource接口内新增了getCompletedPositions()函数，才遇到的新的问题。
