### ISSUE TITLE
为什么 PrestoSQL 官方支持了 Phoenix，而不是直接支持 HBase 呢？

### ISSUE THREAD

**Issue by asdf2014** [analysys/presto-hbase-connector#44]

**Comment by Crossoverrr** [comment]
我认为这有可能是因为我们已经开源了presto-hbase组件，所以prestosql不需要重复开源了吧。  ;)

**Comment by asdf2014** [comment]
哈哈 厉害了

**Comment by asdf2014** [comment]
@Crossoverrr 有计划给 PrestoSQL 提 PR，合并到 PrestoSQL 主分支呢

**Comment by asdf2014** [comment]
@Crossoverrr 有计划给 PrestoSQL 提 PR，合并到 PrestoSQL 主分支吗

**Comment by Crossoverrr** [comment]
你好！
一直都有这个打算，但这个因为是connector级别的贡献，涉及代码很多，会牵扯到很多精力。靠一个人的努力，如果没有完整的时间很难走完全程，我不怕走不通，我怕走到一半无力为继。现在还好的是connector已经支持了presto最新的接口，二次开发或者普通使用的需求是可以满足的。  :)

**Comment by asdf2014** [comment]
@Crossoverrr 是的，估计光 review 代码就要一个月，期待早日合入 PrestoSQL 主分支 :+1:
